name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Run build script
        run: ./bin/build.sh
        shell: bash

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run test script
        run: ./bin/test.sh
        shell: bash